import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { AuthProvider } from "@/lib/AuthProvider";
import { EdgeStoreProvider } from "@/lib/edgestore";
import Header from "@/components/global/Header";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ecommerce prisma",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={`${inter.className} antialiased`}>
          <EdgeStoreProvider>
            <Header />
            {children}
          </EdgeStoreProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
